import { useEffect, useState, type FormEvent } from "react";
import { supabase } from "@/lib/supabaseClient";

type Mode="minimum"|"lower_half"|"maximum"; type Period="day"|"week"|"month";
type Policy={mode:Mode;periodType:Period;startsOn:string;endsOn:string;enabled:boolean;version:number;updatedAt?:string};
const modes=[{id:"minimum" as Mode,name:"Mínimo",ranges:"Diario 1% · 7 días 2% · 14 días 3% · 21 días 4%"},{id:"lower_half" as Mode,name:"Mitad inferior variable",ranges:"Diario 1%–1.25% · 7 días 2%–2.5% · 14 días 3%–3.5% · 21 días 4%–4.5%"},{id:"maximum" as Mode,name:"Máximo",ranges:"Diario 1.5% · 7 días 3% · 14 días 4% · 21 días 5%"}];
const today=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Santo_Domingo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
function endDate(start:string,period:Period){const d=new Date(`${start}T12:00:00Z`);if(period==="week")d.setUTCDate(d.getUTCDate()+6);if(period==="month")d.setUTCMonth(d.getUTCMonth()+1,0);return d.toISOString().slice(0,10)}
async function call(body?:Policy){const token=(await supabase?.auth.getSession())?.data.session?.access_token;if(!token)throw Error("Sesión administrativa requerida.");const r=await fetch("/api/admin/node-reward-policy",{method:body?"PUT":"GET",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json().catch(()=>null);if(!r.ok)throw Error(data?.error||"No se pudo procesar la política.");return data as Policy|null}
export function MonthlyRoiControl(){
 const [policy,setPolicy]=useState<Policy>({mode:"lower_half",periodType:"week",startsOn:today,endsOn:endDate(today,"week"),enabled:true,version:0});const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");
 useEffect(()=>{void call().then(data=>{if(data)setPolicy(data)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 function changePeriod(periodType:Period,startsOn=policy.startsOn){setPolicy(p=>({...p,periodType,startsOn,endsOn:endDate(startsOn,periodType)}));setMessage("")}
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setError("");try{const saved=await call(policy);if(saved)setPolicy(saved);setMessage("Política guardada. Se aplicará a los próximos pagos dentro del período.")}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo guardar.")}finally{setSaving(false)}}
 return <article className="admin-card admin-card-full admin-monthly-roi"><div className="card-heading"><div><p className="admin-kicker">CONTROL MANUAL DE RENDIMIENTOS</p><h2>Política de pago de nodos</h2></div><span className="card-status">{policy.enabled?"ACTIVA":"RANGO NORMAL"}</span></div>
 <p className="config-note">Elige el nivel y cuánto tiempo estará vigente. Solo afecta pagos futuros y los nodos continúan pagando únicamente de lunes a viernes.</p><form onSubmit={save}>
 <div className="admin-roi-grid">{modes.map(m=><label key={m.id}><input type="radio" name="mode" checked={policy.mode===m.id} onChange={()=>setPolicy(p=>({...p,mode:m.id,enabled:true}))}/><strong>{m.name}</strong><small>{m.ranges}</small></label>)}</div>
 <div className="admin-roi-grid"><label>Duración<select value={policy.periodType} onChange={e=>changePeriod(e.target.value as Period)}><option value="day">Un día</option><option value="week">Una semana</option><option value="month">Un mes</option></select></label><label>Comienza<input type="date" value={policy.startsOn} onChange={e=>changePeriod(policy.periodType,e.target.value)}/></label><label>Finaliza<input type="date" value={policy.endsOn} readOnly/></label></div>
 <div className="admin-monthly-preview"><span>VISTA PREVIA</span><strong>{modes.find(m=>m.id===policy.mode)?.ranges}</strong><small>{policy.startsOn} al {policy.endsOn} · hora de Santo Domingo</small></div>
 <button className="admin-user-save" disabled={loading||saving}>{saving?"Guardando…":"Activar política"}</button><button className="admin-user-save" type="button" disabled={saving} onClick={()=>setPolicy(p=>({...p,enabled:false}))}>Volver al rango normal</button>{error&&<p className="form-error">{error}</p>}{message&&<p className="form-success">{message}</p>}</form></article>
}
